### ISSUE TITLE
Mistakes Option

### ISSUE THREAD

**Issue by Bob24477** [EddieDover/NoteCrafter#12]
A "mistakes" option. Select an option so 1 in every "x" amount of words has a mistake. Where an intended word is misspelled and crossed out as if the writer made a mistake while writing.

Pretty much exactly what https://www.scriptalizer.co.uk/scriptalizer.aspx does.

Here's an output example...
![mistake example](https://github.com/user-attachments/assets/dcec96ed-274a-48b8-8ae5-de2d2ecfeaa2)

**Comment by EddieDover** [comment]
Intentionally misspelling a complete word, as shown, requires A) the word be real, and B) the word be English (or the language be something that's customizable). Given the effort to implement it that way, vs the amount of people I think would use it, I don't think it's a valid request.

However, what I could do is perhaps make every 1 in X amount of words have flub a letter, then scribble it and start over.  For example if you typed:
    "I want to eat a bowl of cherries"
the system would pick a word bigger than three letters and flub it, then correct it like:
    "I want to eat a <strike>boe</strike> bowl of cherries"

The effort required in the latter case would simply be verifying the word length, then picking a random letter that didn't match either the previous letter or the letter it's supposed to be.

Still not 100% I can strike the letter properly, but it should be doable.

ASIDE from that, what if I were to figure out a way  to let you use a moustache or bbcode syntax so you could do the errors yourself, treating something like:
"I want to eat a {{strike}}bowel{{/strike}} bowl of cherries" or "I want to eat a [strike]bowel[/strike] bowl of cherries"
displaying it as
"I want to eat a <strike>bowel</strike> bowl of cherries"

**Comment by Bob24477** [comment]
Having it randomly pick a word is "easier" for the user. But purposely misspelling a word and strike theoughing it seems a helluva alot easier to do on your end and gives the user more freedom to misspell a word a specific way.

In regards to strikingthrough, would you be able to add a more organic strikethough that varies? Something that isn't perfectly straight and isn't the same exact mark everytime and is more akin to a someone who barely knows his letters and gets frustrated and strikes strikesthrough unevenly.

**Comment by EddieDover** [comment]
> In regards to strikingthrough, would you be able to add a more organic strikethough that varies? Something that isn't perfectly straight and isn't the same exact mark everytime and is more akin to a someone who barely knows his letters and gets frustrated and strikes strikesthrough unevenly.

I doubt it could be done easily. Currently all this tool does is slap down text in a specific font, over/under a few different image layers. There's no complicated rendering code involved and something like this would require a more procedurally generated or AI centric response.

**Comment by Bob24477** [comment]
Okay. I feel like AI would naturally make things significantly more complicated, so probably avoid it.

Out of curiosity, if using mustache or become syntax, would the strikethrough the generic Microsoft word strike through or can you change it to one custom strikethrough?

**Comment by EddieDover** [comment]
>Out of curiosity, if using mustache or become syntax, would the strikethrough the generic Microsoft word strike through or can you change it to one custom strikethrough?

Going with the generic strike through would be as easy as converting the outgoing html to have strike tags around a word.  I'm not sure if that's something that can be styled though. It probably can, I've never looked into it, but I'm not sure how much it would match the font. 

What about misspelling the words yourself and then using overlays with a transparent scratch to cross out the word? Tedious if you want multiple misspelled words but it would give you more customization.

**Comment by Bob24477** [comment]
I didn't think of overlaying strikethroughs.. as long as you can have many overlays then that should work.

Proper flavoring usually is tedious.
