### ISSUE TITLE
Paper Effects

### ISSUE THREAD

**Issue by Bob24477** [EddieDover/NoteCrafter#13]
Parchment Paper Templates with burn marks, blood splatters, dirt, lipstick, etc.

**Comment by EddieDover** [comment]
Honestly this is already doable via either:

1 - Overlays
2 - Downloading the background (via the attribution link at the top) then modifying it yourself and using the modified version as a custom background. 

Unless I'm missing something, I may have to close this issue. Thoughts?

**Comment by Bob24477** [comment]
I figured out the overlays after I typed this. I believe the overlays does resolve this.
